### ISSUE TITLE
Add a new option to show pagantis in only some product pages

### ISSUE THREAD

**Issue by Maofree** [pagantis/prestashop#84] opened 2020-06-30 16:36 UTC
Hi
is it possible to load the pagantis widget only in filtered product pages like for products that have a price over 100€ ?
it makes no sense to show products with a price of 3-5€ for installments of € 1

thanks

**Comment by pgarcess** [comment] 2020-07-01 08:34
Hello,

You can set the minimum_amount to show our payment method: product & checkout.

To set this configuration see this link: https://github.com/pagantis/prestashop/blob/master/Documentation/configuration.md#clipboard-advanced-configuration

Config name: PAGANTIS_DISPLAY_MIN_AMOUNT

We keep tuned
Thanks!

**Comment by Maofree** [comment] 2020-07-01 08:43
hi
why not add a new field in the configuration form?

**Comment by pgarcess** [comment] 2020-07-01 08:50
We have decided to put inside database. We prefer a clear admin panel only with the mandatory fields.

**Comment by bruno-rc** [comment] 2020-09-04 10:30
hi,
I made the modification from the database, but even if I changed the minimum value by putting example 100 it continues to be visible with lower amounts

**Comment by tmeliotpg** [comment] 2020-09-07 10:26
Duplicate of #95

**Closed as completed by tmeliotpg** 2020-09-07 10:26 UTC
